baseURL = 'http://localhost:1313/'

theme = 'PaperMod'

defaultContentLanguage = 'fr'
defaultContentLanguageInSubdir = true

[languages]

  [languages.fr]
    languageName = 'Français'
    locale = 'fr-FR'
    title = "L'Onde"
    weight = 1

  [languages.en]
    languageName = 'English'
    locale = 'en-US'
    title = 'The wave'
    weight = 2

  [languages.es]
    languageName = 'Español'
    locale = 'es-ES'
    title = 'La ola'
    weight = 3

[params.assets]
customCSS = ["css/extended/custom.css"]
